# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4984de221db4d200d1b9bdb51d45e570c64c15d71fcc7ee20e7b6903f98c5d8c0a773ad13ee45dc10feddab59bee2d968ae5fc9d804f500750981bc634c2c1eb

test:
  secret_key_base: 01dd1e72a4994fb9b28cfd3ff030ace305822b8b530b2a36a8afe6c75fcc30d5f5be28d8494904f80bfad1653a774a6a4067f758249d2b7f10b86cdaceec0207

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
